version: '2'
services:
  psychologically_test_backend-app:
    image: psychologically_test_backend
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psychologically_test_backend-postgresql:5432/psychologically_test_backend
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  psychologically_test_backend-postgresql:
    extends:
      file: postgresql.yml
      service: psychologically_test_backend-postgresql
