export const enum Psychotype {
  EXTRAVERSION_TYPE = 'EXTRAVERSION_TYPE',

  SPONTANEITY_TYPE = 'SPONTANEITY_TYPE',

  AGGRESSIVENESS_TYPE = 'AGGRESSIVENESS_TYPE',

  RIGIDITY_TYPE = 'RIGIDITY_TYPE',

  INTROVERSION_TYPE = 'INTROVERSION_TYPE',

  SENSITIVITY_TYPE = 'SENSITIVITY_TYPE',

  ANXIETY_TYPE = 'ANXIETY_TYPE',

  LABILITY_TYPE = 'LABILITY_TYPE',

  LIE_TYPE = 'LIE_TYPE',

  AGGRAVATION_TYPE = 'AGGRAVATION_TYPE',
}
